export const MockProductListBox = [
    {
        value: 101001,
        desc: 'Chi Nhánh Bình Định',
    },
    {
        value: 101222,
        desc: 'Chi Nhánh Trương Định',
    },
    {
        value: 100740,
        desc: 'Chi Nhánh Đà Nẵng',
    },
    {
        value: 100631,
        desc: 'Cửa hàng cấp 1 của Dứa',
    },
    {
        value: 101100,
        desc: 'đv con số 100',
    },
]
export const MockUserList = [
    {
        role: 'Nhân viên',
        email: 'jxiitwbwb@emlpro.com',
        phone: '0919201212',
        avatar: null,
        status: 1,
        role_id: 5,
        user_id: 76,
        fullname: 'Nguyễn Ngọc Hà',
        language: 'vn',
        username: 'hang',
        master_id: null,
        creator_id: 13,
        last_login: '24/08/2020 15:29:28',
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '24/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
    {
        role: 'Admin',
        email: 'uoxznkzwc@emltmp.com',
        phone: '0988765342',
        avatar: null,
        status: 1,
        role_id: 3,
        user_id: 65,
        fullname: 'Trần Thị Thơm1111',
        language: 'vn',
        username: 'thomtth',
        master_id: null,
        creator_id: 13,
        last_login: null,
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '20/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
    {
        role: 'Admin',
        email: 'jxnvfkdc@netmail.tk',
        phone: '0367977081',
        avatar: null,
        status: 1,
        role_id: 3,
        user_id: 60,
        fullname: 'Trần Thị BA',
        language: 'vn',
        username: 'batt',
        master_id: null,
        creator_id: 13,
        last_login: '20/08/2020 10:41:26',
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '19/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'mkim.jayoun3@bepdfmanuales.xyz',
        phone: '0321456384',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 31,
        fullname: 'vinh',
        language: 'vn',
        username: 'vinhlelele',
        master_id: 100631,
        creator_id: 13,
        last_login: '18/08/2020 10:16:53',
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '18/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'mkim.jayoun3@michaeldurante.com',
        phone: '0321469857',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 30,
        fullname: 'vinh',
        language: 'vn',
        username: 'vinhlele',
        master_id: 100631,
        creator_id: 13,
        last_login: null,
        merchant_id: 101001,
        status_name: 'Hoạt động',
        created_date: '18/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '101001',
            bizname: 'Chi Nhánh Bình Định',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'vtiutkxh@zeroe.ml',
        phone: '0987744556',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 27,
        fullname: 'Lê Văn Đức 1121',
        language: 'vn',
        username: 'duclv',
        master_id: 100631,
        creator_id: 13,
        last_login: '17/08/2020 15:48:32',
        merchant_id: 101001,
        status_name: 'Hoạt động',
        created_date: '17/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '101001',
            bizname: 'Chi Nhánh Bình Định',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'xumuhxwh@laste.ml',
        phone: '0988744565',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 26,
        fullname: 'Trần Đức Dũng',
        language: 'vn',
        username: 'dungdt',
        master_id: 100631,
        creator_id: 13,
        last_login: '17/08/2020 15:05:38',
        merchant_id: 101001,
        status_name: 'Hoạt động',
        created_date: '17/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '101001',
            bizname: 'Chi Nhánh Bình Định',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'thanh@gmail.com',
        phone: '0988874112',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 25,
        fullname: 'Trần Ngọc Thành',
        language: 'vn',
        username: 'thanh',
        master_id: 100631,
        creator_id: 13,
        last_login: null,
        merchant_id: 101001,
        status_name: 'Hoạt động',
        created_date: '17/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '101001',
            bizname: 'Chi Nhánh Bình Định',
        },
    },
    {
        role: 'Nhân viên ĐVCNNT con',
        email: 'puclgxwh@laste.ml',
        phone: '0988774511',
        avatar: null,
        status: 1,
        role_id: 6,
        user_id: 24,
        fullname: 'Lê Ngọc Hà',
        language: 'vn',
        username: 'hangocle',
        master_id: 100631,
        creator_id: 13,
        last_login: '17/08/2020 15:28:44',
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '17/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
    {
        role: 'Nhân viên',
        email: 'anhnv@gmail.com',
        phone: '0367977088',
        avatar: null,
        status: 1,
        role_id: 5,
        user_id: 23,
        fullname: 'Nguyễn Đức Anh',
        language: 'vn',
        username: 'anhnv',
        master_id: 100631,
        creator_id: 13,
        last_login: null,
        merchant_id: 100631,
        status_name: 'Hoạt động',
        created_date: '17/08/2020',
        creator_name: 'Trần Thị Khómm',
        merchant_info: {
            id: '100631',
            bizname: 'Cửa hàng cấp 1 của Dứa',
        },
    },
]