// for sidebar

export const LeftMenuKeyConfig = [
  {
    menuId: 1,
    menuKey: "left-menu.dashboard",
    url: "/admin/dashboard",
    icon: "dashboard",
  },
  {
    menuId: 2,
    menuKey: "left-menu.transaction.manager",
    url: "/admin/transaction",
    icon: "attach_money",
  },
  {
    menuId: 201,
    menuKey: "left-menu.transaction.payment",
    url: "/admin/transaction-payment",
    icon: "payment",
  },
  {
    menuId: 202,
    menuKey: "left-menu.transaction.refund",
    url: "/admin/transaction-refund",
    icon: "keyboard_return",
  },
  {
    menuId: 3,
    menuKey: "left-menu.report.title",
    url: "/admin/report",
    icon: " insert_chart_outlined",
  },
  {
    menuId: 301,
    menuKey: "left-menu.report.revenue",
    url: "/admin/report/revenue-report",
    icon: "monetization_on",
  },
  {
    menuId: 302,
    menuKey: "left-menu.report.money-transfer",
    url: "/admin/report/money-transfer-report",
    icon: "forward",
  },
  {
    menuId: 303,
    menuKey: "left-menu.report.finalization",
    url: "/admin/report/finalization-report",
    icon: "sync",
  },
  {
    menuId: 304,
    menuKey: "left-menu.report.fee",
    url: "/admin/report/fee-report",
    icon: "money",
  },
  {
    menuId: 4,
    menuKey: "left-menu.cross-check",
    url: "/admin/doi-soat",
    icon: "compare_arrows",
  },
  {
    menuId: 5,
    menuKey: "left-menu.dvcntt-manager.manager",
    url: "/admin/merchant",
    icon: "shop",
  },
  {
    menuId: 501,
    menuKey: "left-menu.dvcntt-manager.profile",
    url: "/admin/merchant/profile",
    icon: "work",
  },
  {
    menuId: 502,
    menuKey: "left-menu.dvcntt-manager.manager-dvcntt",
    url: "/admin/merchant/sub-merchant",
    icon: "broken_image",
  },
  {
    menuId: 503,
    menuKey: "left-menu.dvcntt-manager.qrcode",
    url: "/admin/merchant/qrcode",
    icon: "view_comfy",
  },
  {
    menuId: 6,
    menuKey: "left-menu.ruin-manager.title",
    url: "/admin/risks-blacklist",
    icon: "warning",
  },
  {
    menuId: 601,
    menuKey: "left-menu.ruin-manager.account",
    url: "/admin/risks-blacklist/account",
    icon: "account_balance_wallet",
  },
  {
    menuId: 602,
    menuKey: "left-menu.ruin-manager.card",
    url: "/admin/risks-blacklist/card",
    icon: "credit_card",
  },
  {
    menuId: 603,
    menuKey: "left-menu.ruin-manager.bin",
    url: "/admin/risks-blacklist/bin",
    icon: "card_membership",
  },
  {
    menuId: 604,
    menuKey: "left-menu.ruin-manager.ip",
    url: "/admin/risks-blacklist/ip",
    icon: "perm_scan_wifi",
  },
  {
    menuId: 606,
    menuKey: "left-menu.ruin-manager.transaction",
    url: "/admin/risks-blacklist/transaction",
    icon: "money_off",
  },
  {
    menuId: 7,
    menuKey: "left-menu.user-mangager",
    url: "/admin/user",
    icon: "account_box",
  },
  {
    menuId: 8,
    menuKey: "left-menu.service-info",
    url: "/admin/service-info",
    icon: "local_mall",
  },
  {
    menuId: 9,
    menuKey: "left-menu.e-wallet",
    url: "/admin/e-wallet",
    icon: "account_balance_wallet",
  },
  {
    menuId: 901,
    menuKey: "left-menu.wallet-register",
    url: "/admin/e-wallet/wallet-register",
    icon: "account_circle",
  },
  {
    menuId: 902,
    menuKey: "left-menu.wallet-link",
    url: "/admin/e-wallet/bank-link",
    icon: "link",
  },
  {
    menuId: 903,
    menuKey: "left-menu.wallet-cashin",
    url: "/admin/e-wallet/cashin",
    icon: "add_box",
  },
  {
    menuId: 904,
    menuKey: "left-menu.wallet-cashout",
    url: "/admin/e-wallet/cashout",
    icon: "indeterminate_check_box",
  },
  {
    menuId: 905,
    menuKey: "left-menu.wallet-transfer",
    url: "/admin/e-wallet/transfer",
    icon: "forward",
  },
  {
    menuId: 906,
    menuKey: "left-menu.wallet-behalf-payment",
    url: "/admin/e-wallet/payment",
    icon: "payment",
  },
  {
    menuId: 11,
    menuKey: "left-menu.e-wallet-report.title",
    url: "/admin/wallet-report",
    icon: "insert_chart_outlined",
  },
  {
    menuId: 1101,
    menuKey: "left-menu.e-wallet-report.total-wallet",
    url: "/admin/wallet-report/total-wallet",
    icon: "",
  },
  {
    menuId: 1102,
    menuKey: "left-menu.e-wallet-report.total-transaction",
    url: "/admin/wallet-report/total-transaction",
    icon: "",
  },
  {
    menuId: 1103,
    menuKey: "left-menu.e-wallet-report.top-transaction",
    url: "/admin/wallet-report/top-transaction",
    icon: "",
  },
  {
    menuId: 13,
    menuKey: "statistic.button",
    url: "/admin/statistic",
    icon: "bar_chart",
  },
  {
    menuId: 14,
    menuKey: "left-menu.payment-link",
    url: "/admin/payment-link",
    icon: "link",
  },
  {
    menuId: 15,
    menuKey: "left-menu.create-order",
    url: "/admin/create-order",
    icon: "shop",
  },
];
